from nnunetv2.training.nnUNetTrainer.variants.training_length.nnUNetTrainer_Xepochs_NoMirroring import nnUNetTrainer_250epochs_NoMirroring
from nnunetv2.training.nnUNetTrainer.variants.optimizer.nnUNetTrainerAdam import nnUNetTrainerVanillaAdam, nnUNetTrainerAdam1en3
from nnunetv2.training.nnUNetTrainer.variants.optimizer.nnUNetTrainerAdan import nnUNetTrainerAdan1en3

class nnUNetTrainer_vadam_nm250(nnUNetTrainer_250epochs_NoMirroring, nnUNetTrainerVanillaAdam):
    pass

class nnUNetTrainer_adam1en3_nm250(nnUNetTrainer_250epochs_NoMirroring, nnUNetTrainerAdam1en3):
    pass

class nnUNetTrainer_adan1en3_nm250(nnUNetTrainer_250epochs_NoMirroring, nnUNetTrainerAdan1en3):
    pass

